### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by LeeGoh** [LeeGoh/todolist-github-practice#1]
### 구현하고자 하는 기능
1. Todo 생성
2. Todo 수정
3. Todo 전체 조회
4. Todo id 조회
5. Todo 전체 삭제
6. Todo id 삭제

### 해당 기능을 구현하기 위해 할 일
1. [ ] Entity 작성 (id, title, order, completed)
2. [ ] Service 작성 (create, update, delete)
3. [ ] Repository 작성 (extends JpaRepository)
4. [ ] Controller 작성 (get, post, delete)
